// <auto-generated />
using System;
using Helping_Hands;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Helping_Hands.Migrations
{
    [DbContext(typeof(GRP0452HelpingHandsDBContext))]
    [Migration("20230808024528_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Helping_Hands.Admins", b =>
                {
                    b.Property<int>("AdminUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AdminUserID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminContact")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LineAddress1")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LineAddress2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AdminUserID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Helping_Hands.CareContracts", b =>
                {
                    b.Property<int>("ContractNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContractNumberId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("NurseUserId")
                        .HasColumnName("NurseUserId")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnName("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("WoundDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractNumberId");

                    b.HasIndex("CityId");

                    b.HasIndex("NurseUserId");

                    b.HasIndex("PatientUserId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuburbId");

                    b.ToTable("CareContracts");
                });

            modelBuilder.Entity("Helping_Hands.CareVisits", b =>
                {
                    b.Property<int>("CareVisitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CareVisitsId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan?>("ApproxArriva")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("ContractNumberId")
                        .HasColumnName("ContractNumberId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("DepartTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NurseUserId")
                        .HasColumnName("NurseUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("WoundCondition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareVisitsId");

                    b.HasIndex("ContractNumberId");

                    b.HasIndex("NurseUserId");

                    b.ToTable("CareVisits");
                });

            modelBuilder.Entity("Helping_Hands.ChronicAccoms", b =>
                {
                    b.Property<int>("ChronicAccomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ChronicAccomId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChronicId")
                        .HasColumnName("ChronicId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientUserId")
                        .HasColumnName("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ChronicAccomId");

                    b.HasIndex("ChronicId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("ChronicAccoms");
                });

            modelBuilder.Entity("Helping_Hands.ChronicInfections", b =>
                {
                    b.Property<int>("ChronicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ChronicId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("ChronicId");

                    b.ToTable("ChronicInfections");
                });

            modelBuilder.Entity("Helping_Hands.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CityId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbrev")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Helping_Hands.Data.UserApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Helping_Hands.ImageArchive", b =>
                {
                    b.Property<int>("ImageArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ImageArchiveId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("NpoId")
                        .HasColumnName("NpoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("ImageArchiveId");

                    b.HasIndex("NpoId");

                    b.ToTable("ImageArchive");
                });

            modelBuilder.Entity("Helping_Hands.Managers", b =>
                {
                    b.Property<int>("ManagerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ManagerUserId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LineAddress1")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LineAddress2")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("ManagerContact")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<int?>("NpoId")
                        .HasColumnName("NpoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ManagerUserId");

                    b.HasIndex("CityId");

                    b.HasIndex("NpoId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Helping_Hands.Nurses", b =>
                {
                    b.Property<int>("NurseUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NurseUserId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LineAddress1")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LineAddress2")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NurseCode")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("NurseContact")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("NurseUserId");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("Helping_Hands.Organisations", b =>
                {
                    b.Property<int>("NpoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NpoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LineAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LineAddress2")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NpoNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("WeekDay1")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("WeekDay2")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("NpoId");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Helping_Hands.Patients", b =>
                {
                    b.Property<int>("PatientUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PatientUserId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInfor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LineAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LineAddress2")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NextOfKinContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("NextOfKinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("PatientContact")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("SuburbId")
                        .HasColumnName("SuburbId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("PatientUserId");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Helping_Hands.Provinces", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProvinceId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Helping_Hands.Suburbs", b =>
                {
                    b.Property<int>("SuburbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SuburbId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnName("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("PostalCode")
                        .HasColumnName("Postal_Code")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("SuburbId");

                    b.HasIndex("CityId");

                    b.ToTable("Suburbs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Helping_Hands.CareContracts", b =>
                {
                    b.HasOne("Helping_Hands.Cities", "City")
                        .WithMany("CareContracts")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_CareContracts_Cities")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Nurses", "NurseUser")
                        .WithMany("CareContracts")
                        .HasForeignKey("NurseUserId")
                        .HasConstraintName("FK_CareContracts_Nurses");

                    b.HasOne("Helping_Hands.Patients", "PatientUser")
                        .WithMany("CareContracts")
                        .HasForeignKey("PatientUserId")
                        .HasConstraintName("FK_CareContracts_Patients")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Provinces", "Province")
                        .WithMany("CareContracts")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_CareContracts_Provinces")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Suburbs", "Suburb")
                        .WithMany("CareContracts")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_CareContracts_Suburbs")
                        .IsRequired();
                });

            modelBuilder.Entity("Helping_Hands.CareVisits", b =>
                {
                    b.HasOne("Helping_Hands.CareContracts", "ContractNumber")
                        .WithMany("CareVisits")
                        .HasForeignKey("ContractNumberId")
                        .HasConstraintName("FK_CareVisits_CareContracts")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Nurses", "NurseUser")
                        .WithMany("CareVisits")
                        .HasForeignKey("NurseUserId")
                        .HasConstraintName("FK_CareVisits_Nurses")
                        .IsRequired();
                });

            modelBuilder.Entity("Helping_Hands.ChronicAccoms", b =>
                {
                    b.HasOne("Helping_Hands.ChronicInfections", "Chronic")
                        .WithMany("ChronicAccoms")
                        .HasForeignKey("ChronicId")
                        .HasConstraintName("FK_ChronicAccoms_ChronicInfections");

                    b.HasOne("Helping_Hands.Patients", "PatientUser")
                        .WithMany("ChronicAccoms")
                        .HasForeignKey("PatientUserId")
                        .HasConstraintName("FK_ChronicAccoms_Patients");
                });

            modelBuilder.Entity("Helping_Hands.Cities", b =>
                {
                    b.HasOne("Helping_Hands.Provinces", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_Cities_Provinces")
                        .IsRequired();
                });

            modelBuilder.Entity("Helping_Hands.ImageArchive", b =>
                {
                    b.HasOne("Helping_Hands.Organisations", "Npo")
                        .WithMany("ImageArchive")
                        .HasForeignKey("NpoId")
                        .HasConstraintName("FK_ImageArchive_Organisations");
                });

            modelBuilder.Entity("Helping_Hands.Managers", b =>
                {
                    b.HasOne("Helping_Hands.Cities", "City")
                        .WithMany("Managers")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Managers_Cities");

                    b.HasOne("Helping_Hands.Organisations", "Npo")
                        .WithMany("Managers")
                        .HasForeignKey("NpoId")
                        .HasConstraintName("FK_Managers_Organisations");

                    b.HasOne("Helping_Hands.Provinces", "Province")
                        .WithMany("Managers")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_Managers_Provinces");

                    b.HasOne("Helping_Hands.Suburbs", "Suburb")
                        .WithMany("Managers")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_Managers_Suburbs");
                });

            modelBuilder.Entity("Helping_Hands.Organisations", b =>
                {
                    b.HasOne("Helping_Hands.Cities", "City")
                        .WithMany("Organisations")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Organisations_Cities")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Provinces", "Province")
                        .WithMany("Organisations")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_Organisations_Provinces")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Suburbs", "Suburb")
                        .WithMany("Organisations")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_Organisations_Suburbs")
                        .IsRequired();
                });

            modelBuilder.Entity("Helping_Hands.Patients", b =>
                {
                    b.HasOne("Helping_Hands.Cities", "City")
                        .WithMany("Patients")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Patients_Cities")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Provinces", "Province")
                        .WithMany("Patients")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_Patients_Provinces")
                        .IsRequired();

                    b.HasOne("Helping_Hands.Suburbs", "Suburb")
                        .WithMany("Patients")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_Patients_Suburbs")
                        .IsRequired();
                });

            modelBuilder.Entity("Helping_Hands.Suburbs", b =>
                {
                    b.HasOne("Helping_Hands.Cities", "City")
                        .WithMany("Suburbs")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Suburbs_Cities")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Helping_Hands.Data.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Helping_Hands.Data.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helping_Hands.Data.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Helping_Hands.Data.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
